export const GET_TASK = 'GET TASK';

export const GET_TASK_SUCCESS = 'GET TASK SUCCESS';

export const GET_TASK_ERROR = 'GET TASK ERROR';

export const GET_PARENT_TASK = 'GET PARENT TASK';

export const GET_PARENT_TASK_SUCCESS = 'GET PARENT TASK SUCCESS';

export const GET_PARENT_TASK_ERROR = 'GET PARENT TASK ERROR';

export const POST_TASK = 'POST TASK';

export const POST_TASK_SUCCESS = 'POST TASK SUCCESS';

export const POST_TASK_ERROR = 'POST TASK ERROR';

export const PUT_TASK = 'PUT TASK';

export const PUT_TASK_SUCCESS = 'PUT TASK SUCCESS';

export const PUT_TASK_ERROR = 'PUT TASK ERROR';

export const DELETE_TASK = 'DELETE TASK';

export const DELETE_TASK_SUCCESS = 'DELETE TASK SUCCESS';

export const DELETE_TASK_ERROR = 'DELETE TASK ERROR';

export const GET_USER = 'GET USER';

export const GET_USER_SUCCESS = 'GET USER SUCCESS';

export const GET_USER_ERROR = 'GET USER ERROR';

export const POST_USER = 'POST USER';

export const POST_USER_SUCCESS = 'POST USER SUCCESS';

export const POST_USER_ERROR = 'POST USER ERROR';

export const PUT_USER = 'PUT USER';

export const PUT_USER_SUCCESS = 'PUT USER SUCCESS';

export const PUT_USER_ERROR = 'PUT USER ERROR';

export const DELETE_USER = 'DELETE USER';

export const DELETE_USER_SUCCESS = 'DELETE USER SUCCESS';

export const DELETE_USER_ERROR = 'DELETE USER ERROR';

export const GET_PROJECT = 'GET PROJECT';

export const GET_PROJECT_SUCCESS = 'GET PROJECT SUCCESS';

export const GET_PROJECT_ERROR = 'GET PROJECT ERROR';

export const POST_PROJECT = 'POST PROJECT';

export const POST_PROJECT_SUCCESS = 'POST PROJECT SUCCESS';

export const POST_PROJECT_ERROR = 'POST PROJECT ERROR';

export const PUT_PROJECT = 'PUT PROJECT';

export const PUT_PROJECT_SUCCESS = 'PUT PROJECT SUCCESS';

export const PUT_PROJECT_ERROR = 'PUT PROJECT ERROR';

export const DELETE_PROJECT = 'DELETE PROJECT';

export const DELETE_PROJECT_SUCCESS = 'DELETE PROJECT SUCCESS';

export const DELETE_PROJECT_ERROR = 'DELETE PROJECT ERROR';